CinemaApp/Controllers/MovieController.cs
using CinemaApp.Services.Core.Interfaces;
using CinemaApp.Web.ViewModels.Movie;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Common;
using static CinemaApp.Web.ViewModels.ValidationMessages.Movie;

namespace CinemaApp.Web.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService movieService;
        public MovieController(IMovieService movieService)
        {
            this.movieService = movieService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<AllMoviesIndexViewModel> allMovies = await this.movieService
                .GetAllMoviesAsync();

            return View(allMovies);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(MovieFormInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            try
            {
                await this.movieService.AddMovieAsync(inputModel);
                return this.RedirectToAction(nameof(Index));
            }
            catch(Exception e) 
            {
                Console.WriteLine(e.Message);

                this.ModelState.AddModelError(string.Empty, ServiceCreateError);
                return this.View(inputModel);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(string? id)
        {
            try
            {
                MovieDetailsViewModel? movieDetails = await movieService
                    .GetMovieDetailsByIdAsync(id);

                if(movieDetails == null)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View(movieDetails);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            try
            {
                MovieFormInputModel? editableMovie= await this.movieService
                    .GetEditableMovieByIdAsync(id);

                if(editableMovie == null)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View(editableMovie);
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MovieFormInputModel inputModel)
        {
            if(!ModelState.IsValid)
            {
                return View(inputModel);
            }

            try
            {
                bool result = await movieService.EditMovieAsync(inputModel);

                if(!result)
                {
                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction(nameof(Details), new {id=inputModel.Id});
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            try
            {
                DeleteMovieViewModel? movieToBeDeleted = await this.movieService
                    .GetMovieDeleteDetailsByIdAsync(id);
                if (movieToBeDeleted == null)
                {
                    return this.RedirectToAction(nameof(Index));
                }

                return this.View(movieToBeDeleted);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);

                return this.RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(DeleteMovieViewModel inputModel)
        {
            try
            {
                if (!this.ModelState.IsValid)
                {
                    return this.RedirectToAction(nameof(Index));
                }

                bool deleteResult = await this.movieService
                    .SoftDeleteMovieAsync(inputModel.Id);
                if (deleteResult == false)
                {
                    return this.RedirectToAction(nameof(Index));
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);

                return this.RedirectToAction(nameof(Index));
            }
        }
    }
}

CinemaApp/Controllers/WatchlistController.cs
using CinemaApp.Web.ViewModels.Watchlist;
using Microsoft.AspNetCore.Mvc;

namespace CinemaApp.Web.Controllers
{
    public class WatchlistController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<WatchlistViewModel> emptyWatchlist= new List<WatchlistViewModel>();
            return View(emptyWatchlist);
        }
    }
}

CinemaApp/Views/Shared/_Layout.cshtml
@{
	int currentYear = DateTime.UtcNow.Year;
	string footerNote = (2025 == currentYear) ? $"{currentYear}" : $"{2025} - {currentYear}";
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"]</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/CinemaApp.Web.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

	@*TODO: Remove this and introduce it as section Styles in the page*@
	@if (ViewData["Title"] != null && ViewData["Title"].ToString() == "Explore Cinemas")
	{
		<link rel="stylesheet" href="~/css/cinema.css" asp-append-version="true" />
	}

	@await RenderSectionAsync("Styles", false)

</head>
<body>
	<header>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-lg">
			<div class="container-fluid">
				<a class="navbar-brand fw-bold text-warning" asp-area="" asp-controller="Home" asp-action="Index">
					<i class="bi bi-camera-reels-fill"></i> CinemaWebApp
				</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
						aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-lg-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Movie" asp-action="Index">
								<i class="bi bi-camera-reels"></i> Movies
							</a>
						</li>
						@if (User?.Identity?.IsAuthenticated ?? false)
						{

							<li class="nav-item">
								<a class="nav-link text-light" asp-area="" asp-controller="Watchlist" asp-action="Index">
									<i class="bi bi-bookmark-star"></i> Watchlist
								</a>
							</li>

							<li class="nav-item">
								<a class="nav-link text-light" asp-area="" asp-controller="Movie" asp-action="Add">
									<i class="bi bi-ticket-perforated"></i> Add Movie
								</a>
							</li>
						}

					</ul>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			<p>&copy; @footerNote CinemaWebApp | Bringing Cinema and Movies to You</p>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>